apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 20
  selector:
    matchLabels:
      app: test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        #- image: httpd:2.4.65-alpine3.22
        - image: httpd
          name: httpd
          #command: ["/bin/bash","-c"] #override the default command
          #args: ["sleep 5; exit 1"] #sleep for 30 seconds then exit with an error
